version: "2.4"

networks:
  cs_network:
    name: cs_network

services:
  cs_maria_db:
    image: mariadb:10.6.4
    container_name: cs_maria_db
    expose:
     - "3306"
    ports:
     - 3306
    networks:
     - cs_network
    volumes:
     - ./mdb_tmp:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: "root"    
      MARIADB_DATABASE: "control_systems"
      MARIADB_USER: "control_systems"
      MARIADB_PASSWORD: "control_systems"

  cs_web:
    build:
      dockerfile: DockerfileWeb
    container_name: cs_web
    expose:
      - 9000
    ports:
      - 9000:9000
    networks:
      - cs_network
    depends_on:
      - cs_maria_db

  cs_front:
    build:
      dockerfile: DockerfileFront
    container_name: cs_front
    environment:
     - REACT_APP_BASE_SERVER_URL=http://localhost:9000
     - NODE_OPTIONS=--openssl-legacy-provider --max_old_space_size=2048
    expose:
     - "3000"
    ports:
      - 3000:3000
    networks:
      - cs_network
    depends_on:
      - cs_web
    stdin_open: true
    command: bash -c "ls && npm start"
    
